services:
  backend:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

    build:
      context: ./backend/
      dockerfile: Dockerfile

    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile

    depends_on:
      backend:
        condition: service_started

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres'"]
      interval: 10s
      timeout: 3s
      retries: 3

    ports:
      - "5432:5432"

volumes:
  postgres-data:
