services:
  backend:
    image: ghcr.io/mcfiet/random-draw/backend
    networks:
      - frontend
    environment:
      POSTGRES_HOST: random-draw_db
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
      POSTGRES_USER_FILE: /run/secrets/POSTGRES_USER
      POSTGRES_DB_FILE: /run/secrets/POSTGRES_DB
    secrets:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    depends_on:
      - db
    ports:
      - "3000:3000"

  frontend:
    image: ghcr.io/mcfiet/random-draw/frontend
    networks:
      - frontend
    depends_on:
      - backend

  db:
    image: postgres:latest
    networks:
      - frontend
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
      POSTGRES_USER_FILE: /run/secrets/POSTGRES_USER
      POSTGRES_DB_FILE: /run/secrets/POSTGRES_DB
    secrets:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres'"]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - "5432:5432"

secrets:
  POSTGRES_PASSWORD:
    external: true
  POSTGRES_USER:
    external: true
  POSTGRES_DB:
    external: true

volumes:
  postgres-data:

networks:
  frontend:
    external: true
